import random
insults = ["I\'m not saying I hate you, but I would unplug your life support to charge my phone.",
           "Roses are red, violets are blue, I have 5 fingers, the 3rd one\'s for you.",
           "You\'re so ugly, when your mom dropped you off at school she got a fine for littering.",
           "I bet your brain feels as good as new, seeing that you never use it.",
           "I wasn\'t born with enough middle fingers to let you know how I feel about you.",
           "I\'m jealous of all the people that haven't met you!",
           "You bring everyone a lot of joy, when you leave the room.",
           "I\'d like to see things from your point of view but I can\'t seem to get my head that far up my ass.",
           "I could eat a bowl of alphabet soup and shit out a smarter statement than that.",
           "If laughter is the best medicine, your face must be curing the world.",
           "If I wanted to kill myself I\'d climb your ego and jump to your IQ.",
           "Your family tree must be a cactus because everybody on it is a prick.",
           "There\'s only one problem with your face, I can see it.",
           "You\'re so ugly, when you popped out the doctor said \"Aww, what a treasure\" and your mom said \"Yeah, lets bury it.\"",
           "If you\'re gonna be a smartass, first you have to be smart. Otherwise you\'re just an ass.",
           "I don\'t exactly hate you, but if you were on fire and I had water, I\'d drink it.",
           "It\'s better to let someone think you are an idiot than to open your mouth and prove it.",
           "You shouldn\'t play hide and seek, no one would look for you.",
           "How many times do I have to flush to get rid of you?",
           "Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology.",
           "Roses are red violets are blue, God made me pretty, what happened to you?",
           "I'd slap you, but shit stains.",
           "What are you going to do for a face when the baboon wants his butt back?",
           "I have neither the time nor the crayons to explain this to you.",
           "Do you know how long it takes for your mother to take a crap? Nine months.",
           "If I gave you a penny for your thoughts, I'd get change.",
           "I may love to shop but I'm not buying your bullshit.",
           "You have two brains cells, one is lost and the other is out looking for it.",
           "If I were to slap you, it would be considered animal abuse!",
           "You're the reason the gene pool needs a lifeguard.",
           "Why don't you slip into something more comfortable -- like a coma.",
           "Well I could agree with you, but then we'd both be wrong.",
           "It looks like your face caught on fire and someone tried to put it out with a hammer.",
           "You're so ugly, the only dates you get are on a calendar.",
           "You're not funny, but your life, now that's a joke.",
           "What are you doing here? Did someone leave your cage open?",
           "I'd like to kick you in the teeth, but that would be an improvement!",
           "Why don't you check eBay and see if they have a life for sale.",
           "You're so ugly, you scared the crap out of the toilet.",
           "If you spoke your mind, you'd be speechless.",
           "You're so ugly, when you got robbed, the robbers made you wear their masks.",
           "I'll never forget the first time we met, although I'll keep trying.",
           "You're as bright as a black hole, and twice as dense.",
           "So you've changed your mind, does this one work any better?",
           "You're so ugly you make blind kids cry.",
           "You are proof that evolution CAN go in reverse.",
           "You're a person of rare intelligence. It's rare when you show any.",
           "Your face makes onions cry.",
           "Your parents hated you so much your bath toys were an iron and a toaster",
           "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
           "I heard your parents took you to a dog show and you won.",
           "If your brain was made of chocolate, it wouldn't fill an M&M.",
           "Two wrongs don't make a right, take your parents as an example.",
           "I'm glad to see you're not letting your education get in the way of your ignorance.",
           "What language are you speaking? Cause it sounds like bullshit.",
           "You so ugly when who were born the doctor threw you out the window and the window threw you back.",
           "Ordinarily people live and learn. You just live.",
           "Calling you an idiot would be an insult to all stupid people.",
           "I was going to give him a nasty look, but he already had one.",
           "Support bacteria - they're the only culture some people have.",
           "If I wanted to hear from an asshole, I'd fart.",
           "When you were born, the doctor came out to the waiting room and said to your father, \"I'm very sorry. We did everything we could. But he pulled through.\"",
           "You've got two brain cells: one is in a wheelchair and the other one is pushing.",
           "Your gene pool could use a little chlorine."]
           
def getRandomInsult():
    return random.choice(insults)
    
